name: edp-springboot-helloworld
namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: gcp.edp-epam.com


database:
  required: true
  version: postgres:9.6
  storageClass: standard
  capacity: 1Mi



ingress:
  required: true
  site: helloworld
  path: /

image:
  name: edp-springboot-helloworld
  version: latest